import { useLoans } from '../../context/LoanServiceProvider';
import { STAGES } from '../../data/stages';

function fmtCurrency(n: number): string {
  if (n >= 1_000_000) return `$${(n / 1_000_000).toFixed(2)}M`;
  if (n >= 1_000)     return `$${(n / 1_000).toFixed(0)}k`;
  return `$${n}`;
}

function fmtDate(iso: string | null): string {
  if (!iso) return '—';
  return new Date(iso).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
}

function fmtLtv(ltv: number | undefined): string {
  if (ltv == null) return '—';
  return `${(ltv * 100).toFixed(1)}%`;
}

function fmtRate(rate: number): string {
  return `${rate.toFixed(2)}%`;
}

const stageMap = new Map(STAGES.map(s => [s.id, s.name]));

export function PrintView() {
  const { loans } = useLoans();
  const today = new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });

  return (
    <div className="print-view">
      <h1>Anchor Point Lending — Loan Portfolio</h1>
      <p className="print-view__date">Printed {today}</p>

      <table>
        <thead>
          <tr>
            <th>Display Label</th>
            <th>Stage</th>
            <th>Amount</th>
            <th>LTV%</th>
            <th>Interest Rate</th>
            <th>Servicer</th>
            <th>Closing Date</th>
            <th>Funded Date</th>
          </tr>
        </thead>
        <tbody>
          {loans.map(loan => (
            <tr key={loan.id}>
              <td>{loan.displayLabel}</td>
              <td>{stageMap.get(loan.stageId) ?? loan.stageId}</td>
              <td>{fmtCurrency(loan.loanAmount)}</td>
              <td>{fmtLtv(loan.computedLtv)}</td>
              <td>{fmtRate(loan.interestRate)}</td>
              <td>{loan.servicer}</td>
              <td>{fmtDate(loan.closingDate)}</td>
              <td>{fmtDate(loan.fundedDate)}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <p className="print-view__footer">
        Total loans: {loans.length} &nbsp;|&nbsp; Generated by Anchor Point Lending Board
      </p>
    </div>
  );
}
